services:
  backend:
    build:
      context: .
    ports:
      - ${BACKEND_PORT:-3000}:3000
    depends-on:
      mongo-db:
        condition:
          service_completed_successfully
    links:
      - mongodb
  mongodb:
    image: docker.io/mongo:latest
    restart: always
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
