services:
  backend:
    build:
      context: .
    ports:
      - ${BACKEND_PORT:-3000}:3000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    depends-on:
      mongo-db:
        condition:
          service_completed_successfully
    links:
      - mongodb
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
  mongodb:
    image: docker.io/mongo:latest
    restart: always
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s


volumes:
  mongodb:
